name: neon_stress_tester
author: eightballer
version: 0.1.0
description: An agent service which allows the stress testing of the neon network,
  by allowing a massive amount of faucet claims.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: eightballer/defi_agent:0.1.0:bafybeiajolwqw77ikcy3hmoubtznfbfcqfirolbiiu5skxutlilmltlvze
number_of_agents: 25
deployment: {}
