version: '3.7'
services:


  prometheus:
    extra_hosts:
        - "host.docker.internal:host-gateway"

    mem_limit: 128m
    cpus: 0.1
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
    user: "1000"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-admin-api
    ports:
      - 9090:9090

  grafana:
    mem_limit: 128m
    cpus: 0.1
    image: grafana/grafana:latest
    ports:
      - ${GRAFANA_PORT:-26658}:3000
    user: "1000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - GF_SECURITY_ALLOW_EMBEDDING=true 
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    volumes:
      - ./data/grafana:/var/lib/grafana  
      - ./grafana-provisioning:/etc/grafana/provisioning

