openapi: 3.0.0
info:
  title: Sample API
  description: Allows claiming for drip faucets.
  version: 0.1.0
servers:
  - url: http://localhost:5000
  - url: http://faucet.rae.cloud
paths:
  /claim:
    options:
      summary: handles_options method for cors
      requestBody:
        required: False
        content:
          application/octet-stream:
            schema:
              type: string

      responses:
        '200':
          description: A Json response
          content:
            application/json:
              schema:
                type: object
    post:
      summary: Posts a claim for a faucet reward
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                public_address:
                  type: string
                  pattern: '0x[a-fA-F0-9]{40}'
                ledger_id:
                  type: string
              required:
                - public_address
                - ledger_id
      responses:
        '201':
          description: A Json response
          content:
            application/json:
              schema:
                type: object


