name: multichain_faucet
author: eightballer
version: 0.1.0
description: An agent service which allows the agent to interact cross chain and cross
  platform acting as a faucet for holders of olas.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: eightballer/defi_agent:0.1.0:bafybeie6xlavcmyh6sm3wfwz7ecujhm3enmayym7ivqpgmedcyy27eyykm
number_of_agents: 1
deployment: {}
