agent_name: defi_agent
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.35.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/prometheus:0.1.1:bafybeibc5x4ldgtl7jrgz4vjtbm3o6bf2zeyfsa47vftbpeszotl3x2knm
- valory/ledger:0.19.0:bafybeibiskshuj4nr5ttrg7dhb6izqh3w2xhjzo7ljhdh6h5ruv3rhhluy
contracts:
- eightballer/erc_20:0.1.0:bafybeihzyver74cyqzngkzicirjnrphg464hzsyflngosrda7ickmvapzi
protocols:
- eightballer/http:0.1.0:bafybeibels7dv7ucflaeniwifbisvkegm5vrarrr5ctkcqebg4t7onba6a
- eightballer/prometheus:1.0.0:bafybeidg56u4eza6z3pqkpcqw5cvobjar6azi5yko4joaosb2ev5buqrdq
- open_aea/signing:1.0.0:bafybeig7ijceilgb22q7yg65jok7n5bmo3uogezpz4tltmil2xh7ib6e5q
- valory/contract_api:1.0.0:bafybeib3abpck4a6a63vyymd2pdiwijdsqk43hrrxz734v5ghxje46pxgm
- valory/http:1.0.0:bafybeieshrrplt5oadws5tz3rhjo6m2spchdyhkwa2z6ze2bs4ivauusfq
- valory/ledger_api:1.0.0:bafybeidltb2fvcfokf7a2i3jnrf4kmmsn5bxmcrwdtbz2nrrzhpj4dlzwe
skills:
- eightballer/balance_metrics:0.1.0:bafybeifiigtc74lzhvyiplrna7jl2mz5pkcwpiawa6lprde5usgb4xsusm
- eightballer/prometheus:0.1.0:bafybeid3wfmcdwagudn6xnc32blf2vgtxc35ymricoz3jqvonzv3i66eii
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    matic:
      address: ${str:https://rpc.ankr.com/polygon}
      chain_id: ${int:137}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
    ethereum:
      address: ${str:https://rpc.mevblocker.io}
      chain_id: ${int:1}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: eightballer/balance_metrics:0.1.0:bafybeifrzxs3gbetwhc5kgvfq3tri7wfx6gzo5fdlfdfycmbrrynkp6a5q
type: skill
models:
  balance_metrics_strategy:
    args:
      ledger_ids:
      - ethereum
      - filecoin
      - gnosis
      - matic
      - scroll
      - spark
      - mantle
      prometheus_enabled: true
      token_addresses: {}
---
public_id: eightballer/prometheus:0.1.1:bafybeibc5x4ldgtl7jrgz4vjtbm3o6bf2zeyfsa47vftbpeszotl3x2knm
type: connection
config:
  host: ${str:0.0.0.0}
  port: ${int:8888}
---
public_id: eightballer/prometheus:0.1.0:bafybeieq7ioolzjrxh2whdcdn6sfwwunwtnuiph5e45kx2hl667a6vcqta
type: skill
is_abstract: true
