agent_name: defi_agent
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.35.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/prometheus:0.1.1:bafybeibc5x4ldgtl7jrgz4vjtbm3o6bf2zeyfsa47vftbpeszotl3x2knm
- eightballer/http_server:0.1.0:bafybeifvztshvoeie6mghz23z75he4jns2bs3p64l4rb2tf5ausevcuti4
- eightballer/http_client:0.1.0:bafybeifn24kz3rv2myfxvz2jisiz6p76f7kgxwuibggkmxbvpv74thensq
- valory/ledger:0.19.0:bafybeihtho6skcdtmfzy3ho5tf3wqemzojphzgupqj52cz2z2fpxycou2y
contracts:
- eightballer/erc_20:0.1.0:bafybeihzyver74cyqzngkzicirjnrphg464hzsyflngosrda7ickmvapzi
protocols:
- eightballer/default:0.1.0:bafybeicj23oli6dvzj22sfvtfc46duqzvbpis5yskq5f5t55qikvwjtfme
- eightballer/fipa:0.1.0:bafybeief7f7xh6lgqiqtk333jwdec7occpvlalankbwvrhndxupt44brja
- eightballer/http:0.1.0:bafybeibels7dv7ucflaeniwifbisvkegm5vrarrr5ctkcqebg4t7onba6a
- eightballer/prometheus:1.0.0:bafybeidg56u4eza6z3pqkpcqw5cvobjar6azi5yko4joaosb2ev5buqrdq
- open_aea/signing:1.0.0:bafybeig7ijceilgb22q7yg65jok7n5bmo3uogezpz4tltmil2xh7ib6e5q
- valory/contract_api:1.0.0:bafybeib3abpck4a6a63vyymd2pdiwijdsqk43hrrxz734v5ghxje46pxgm
- valory/ledger_api:1.0.0:bafybeidltb2fvcfokf7a2i3jnrf4kmmsn5bxmcrwdtbz2nrrzhpj4dlzwe
skills:
- eightballer/balance_metrics:0.1.0:bafybeigjlb7tdf7gl7pviqx2by3g5c673z2j42kazuqbb6rdfllmhoqj2y
- eightballer/faucet:0.1.0:bafybeicaptnlvejgroiswg2ch4k2fk4qh6hicafzy7dpqe5j6pcuba4fdi
- eightballer/prometheus:0.1.0:bafybeif4evjhwa3ac5bdojqs2gi7pvr6evnnwml2gsopktdnc6fx3vr5tu
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: eightballer/balance_metrics:0.1.0:bafybeifrzxs3gbetwhc5kgvfq3tri7wfx6gzo5fdlfdfycmbrrynkp6a5q
type: skill
models:
  balance_metrics_strategy:
    args:
      ledger_ids:
      - ethereum
      - filecoin
      - gnosis
      - matic
      - scroll
      - spark
      - mantle
      prometheus_enabled: true
      token_addresses: {}
---
public_id: eightballer/prometheus:0.1.1:bafybeibc5x4ldgtl7jrgz4vjtbm3o6bf2zeyfsa47vftbpeszotl3x2knm
type: connection
config:
  host: ${str:0.0.0.0}
  port: ${int:8888}
---
public_id: eightballer/prometheus:0.1.0:bafybeieq7ioolzjrxh2whdcdn6sfwwunwtnuiph5e45kx2hl667a6vcqta
type: skill
is_abstract: true
---
public_id: eightballer/faucet:0.1.0:bafybeie24q5y2jbarpfip5k63hzxdt7prywdcglskyo5jep7ec7ap33gzy
type: skill
models:
  strategy:
    args:
      max_requests_per_day: ${int:10}
      gwei_per_request: ${int:1}
      database_uri_string: ${str:sqlite:///faucet.db}
      allow_list: ${list:[]}
      ban_list: ${list:[]}
---
public_id: eightballer/http_server:0.1.0:bafybeia6shz5vnl5j7chaymvetrdrczdnca4huyy7djpgrptww2zaihliy
type: connection
config:
  host: 0.0.0.0
  port: 5000
  target_skill_id: eightballer/faucet:0.1.0
  api_spec_path: vendor/eightballer/skills/faucet/open_api_spec.yaml
