{
 "title": "Agent Balances",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "All Agent Native Balances",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "spark_native_balance", "legendFormat": "__auto" },
    { "expr": "filecoin_native_balance", "legendFormat": "__auto" },
    { "expr": "gnosis_native_balance", "legendFormat": "__auto" },
    { "expr": "mantle_native_balance", "legendFormat": "__auto" },
    { "expr": "matic_native_balance", "legendFormat": "__auto" },
    { "expr": "ethereum_native_balance", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Agent Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 20 },
   "targets": [
    { "expr": "memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Agent CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 20 },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}