openapi: 3.0.0
info:
  title: Sample API
  description: Allows claiming for drip faucets.
  version: 0.1.0
servers:
  - url: http://0.0.0.0:5555
paths:
  /claim:
    options:
      summary: handles_options method for cors
      requestBody:
        required: False
        content:
          application/octet-stream:
            schema:
              type: string

      responses:
        '200':
          description: A Json response
          content:
            application/json:
              schema:
                type: object
    post:
      summary: Posts a claim for a faucet reward
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                public_address:
                  type: string
                  pattern: '0x[a-fA-F0-9]{40}'
                ledger_id:
                  type: string
                  pattern: '^[a-z0-9_]+$'
              required:
                - public_address
                - ledger_id
      responses:
        '201':
          description: A Json response
          content:
            application/json:
              schema:
                type: object
  /ledgers:
    get:
      summary: Returns a list of supported ledgers
      responses:
        '200':
          description: A Json response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ledgers:
                    type: array
  /config:
    get:
      summary: Returns the config of the agent.
      responses:
        '200':
          description: A Json response
          content:
            application/json:
              schema:
                type: object
  /txs:
    get:
      summary: Returns a list of transactions from ther faucet
      responses:
        '200':
          description: A Json response
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array


